/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.flatron.vistas;

import javax.swing.ImageIcon;

/**
 *
 * @author laboratorio
 */
public class VistaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        clienteButton = new javax.swing.JButton();
        informeButton = new javax.swing.JButton();
        productoButton = new javax.swing.JButton();
        proovedoresButton = new javax.swing.JButton();
        ventasButton = new javax.swing.JButton();
        comprasButton = new javax.swing.JButton();
        proveedoresLabel = new javax.swing.JLabel();
        informesLabel = new javax.swing.JLabel();
        productosLabel = new javax.swing.JLabel();
        clientesLabel = new javax.swing.JLabel();
        flatronLabel = new javax.swing.JLabel();
        ventasLabel = new javax.swing.JLabel();
        comprasLabel = new javax.swing.JLabel();
        comodinLabel = new javax.swing.JLabel();
        fondojLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWidths = new int[] {0, 40, 0, 40, 0, 40, 0, 40, 0, 40, 0};
        layout.rowHeights = new int[] {0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0};
        getContentPane().setLayout(layout);

        clienteButton.setBackground(new java.awt.Color(77, 58, 89));
        clienteButton.setForeground(new java.awt.Color(255, 255, 255));
        clienteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/flatron/vistas/imagenes/cliente.png"))); // NOI18N
        clienteButton.setBorder(null);
        clienteButton.setBorderPainted(false);
        clienteButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        clienteButton.setFocusable(false);
        clienteButton.setMaximumSize(new java.awt.Dimension(90, 90));
        clienteButton.setMinimumSize(new java.awt.Dimension(90, 90));
        clienteButton.setPreferredSize(new java.awt.Dimension(90, 90));
        clienteButton.setRequestFocusEnabled(false);
        clienteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonClientesApretado(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 29;
        gridBagConstraints.ipady = 29;
        gridBagConstraints.weightx = 20.0;
        getContentPane().add(clienteButton, gridBagConstraints);

        informeButton.setBackground(new java.awt.Color(89, 58, 58));
        informeButton.setForeground(new java.awt.Color(255, 255, 255));
        informeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/flatron/vistas/imagenes/informe.png"))); // NOI18N
        informeButton.setBorder(null);
        informeButton.setFocusable(false);
        informeButton.setMaximumSize(new java.awt.Dimension(90, 90));
        informeButton.setMinimumSize(new java.awt.Dimension(90, 90));
        informeButton.setPreferredSize(new java.awt.Dimension(90, 90));
        informeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonInformesApretado(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 29;
        gridBagConstraints.ipady = 29;
        gridBagConstraints.weightx = 20.0;
        getContentPane().add(informeButton, gridBagConstraints);

        productoButton.setBackground(new java.awt.Color(64, 89, 58));
        productoButton.setForeground(new java.awt.Color(255, 255, 255));
        productoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/flatron/vistas/imagenes/producto.png"))); // NOI18N
        productoButton.setBorder(null);
        productoButton.setFocusable(false);
        productoButton.setPreferredSize(new java.awt.Dimension(90, 90));
        productoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonProductosApretado(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 29;
        gridBagConstraints.ipady = 29;
        gridBagConstraints.weightx = 20.0;
        getContentPane().add(productoButton, gridBagConstraints);

        proovedoresButton.setBackground(new java.awt.Color(86, 89, 58));
        proovedoresButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/flatron/vistas/imagenes/proveedores.png"))); // NOI18N
        proovedoresButton.setBorder(null);
        proovedoresButton.setFocusable(false);
        proovedoresButton.setPreferredSize(new java.awt.Dimension(90, 90));
        proovedoresButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonProveedoresApretado(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 29;
        gridBagConstraints.ipady = 29;
        gridBagConstraints.weightx = 20.0;
        getContentPane().add(proovedoresButton, gridBagConstraints);

        ventasButton.setBackground(new java.awt.Color(39, 58, 86));
        ventasButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/flatron/vistas/imagenes/venta.png"))); // NOI18N
        ventasButton.setBorder(null);
        ventasButton.setPreferredSize(new java.awt.Dimension(90, 90));
        ventasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVentasApretado(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 29;
        gridBagConstraints.ipady = 29;
        gridBagConstraints.weightx = 20.0;
        getContentPane().add(ventasButton, gridBagConstraints);

        comprasButton.setBackground(new java.awt.Color(131, 132, 90));
        comprasButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/flatron/vistas/imagenes/compra.png"))); // NOI18N
        comprasButton.setBorder(null);
        comprasButton.setBorderPainted(false);
        comprasButton.setFocusable(false);
        comprasButton.setPreferredSize(new java.awt.Dimension(90, 90));
        comprasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonComprasApretado(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 29;
        gridBagConstraints.ipady = 29;
        gridBagConstraints.weightx = 20.0;
        getContentPane().add(comprasButton, gridBagConstraints);

        proveedoresLabel.setBackground(new java.awt.Color(0, 0, 0));
        proveedoresLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        proveedoresLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        proveedoresLabel.setText("PROVEEDORES");
        proveedoresLabel.setPreferredSize(new java.awt.Dimension(90, 19));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 36;
        gridBagConstraints.ipady = 20;
        getContentPane().add(proveedoresLabel, gridBagConstraints);

        informesLabel.setBackground(new java.awt.Color(0, 0, 0));
        informesLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        informesLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        informesLabel.setText("INFORMES");
        informesLabel.setPreferredSize(new java.awt.Dimension(90, 19));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.ipadx = 36;
        gridBagConstraints.ipady = 20;
        getContentPane().add(informesLabel, gridBagConstraints);

        productosLabel.setBackground(new java.awt.Color(0, 0, 0));
        productosLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        productosLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        productosLabel.setText("PRODUCTOS");
        productosLabel.setPreferredSize(new java.awt.Dimension(90, 19));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 36;
        gridBagConstraints.ipady = 20;
        getContentPane().add(productosLabel, gridBagConstraints);

        clientesLabel.setBackground(new java.awt.Color(0, 0, 0));
        clientesLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        clientesLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        clientesLabel.setText("CLIENTES ");
        clientesLabel.setPreferredSize(new java.awt.Dimension(90, 19));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 36;
        gridBagConstraints.ipady = 20;
        getContentPane().add(clientesLabel, gridBagConstraints);

        flatronLabel.setBackground(new java.awt.Color(0, 0, 0));
        flatronLabel.setFont(new java.awt.Font("Comic Sans MS", 3, 24)); // NOI18N
        flatronLabel.setForeground(new java.awt.Color(51, 51, 51));
        flatronLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        flatronLabel.setText("Flatron");
        flatronLabel.setPreferredSize(new java.awt.Dimension(90, 19));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 7;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(flatronLabel, gridBagConstraints);

        ventasLabel.setBackground(new java.awt.Color(0, 0, 0));
        ventasLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ventasLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ventasLabel.setText("VENTAS");
        ventasLabel.setPreferredSize(new java.awt.Dimension(90, 19));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.ipadx = 36;
        gridBagConstraints.ipady = 20;
        getContentPane().add(ventasLabel, gridBagConstraints);

        comprasLabel.setBackground(new java.awt.Color(0, 0, 0));
        comprasLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        comprasLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        comprasLabel.setText("COMPRAS");
        comprasLabel.setPreferredSize(new java.awt.Dimension(90, 19));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.ipadx = 36;
        gridBagConstraints.ipady = 20;
        getContentPane().add(comprasLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(comodinLabel, gridBagConstraints);

        fondojLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/flatron/vistas/imagenes/fondo.jpg"))); // NOI18N
        fondojLabel.setMaximumSize(new java.awt.Dimension(5000, 4000));
        fondojLabel.setPreferredSize(new java.awt.Dimension(2700, 1600));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 11;
        gridBagConstraints.gridheight = 13;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = -1990;
        gridBagConstraints.ipady = -1200;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 0.001;
        gridBagConstraints.weighty = 0.001;
        getContentPane().add(fondojLabel, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonVentasApretado(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVentasApretado
        // TODO add your handling code here:
    }//GEN-LAST:event_botonVentasApretado

    private void botonProveedoresApretado(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonProveedoresApretado
        // TODO add your handling code here:
    }//GEN-LAST:event_botonProveedoresApretado

    private void botonComprasApretado(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonComprasApretado
        // TODO add your handling code here:
    }//GEN-LAST:event_botonComprasApretado

    private void botonInformesApretado(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonInformesApretado
        // TODO add your handling code here:
    }//GEN-LAST:event_botonInformesApretado

    private void botonProductosApretado(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonProductosApretado
        // TODO add your handling code here:
    }//GEN-LAST:event_botonProductosApretado

    private void botonClientesApretado(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonClientesApretado
        // TODO add your handling code here:
    }//GEN-LAST:event_botonClientesApretado

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clienteButton;
    private javax.swing.JLabel clientesLabel;
    private javax.swing.JLabel comodinLabel;
    private javax.swing.JButton comprasButton;
    private javax.swing.JLabel comprasLabel;
    private javax.swing.JLabel flatronLabel;
    private javax.swing.JLabel fondojLabel;
    private javax.swing.JButton informeButton;
    private javax.swing.JLabel informesLabel;
    private javax.swing.JButton productoButton;
    private javax.swing.JLabel productosLabel;
    private javax.swing.JButton proovedoresButton;
    private javax.swing.JLabel proveedoresLabel;
    private javax.swing.JButton ventasButton;
    private javax.swing.JLabel ventasLabel;
    // End of variables declaration//GEN-END:variables
}
