/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.flatron.vistas;

/**
 *
 * @author laboratorio
 */
public class VistaUnidadMedida extends javax.swing.JFrame {

    /**
     * Creates new form VistaUnidadMedida
     */
    public VistaUnidadMedida() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        nombreUnidadMedidaLabel = new javax.swing.JLabel();
        simboloUnidadMedidaLabel = new javax.swing.JLabel();
        simboloTextField = new javax.swing.JTextField();
        nombreTextField = new javax.swing.JTextField();
        guardarUnidadMedidaButton = new javax.swing.JButton();
        eliminarUnidadMedidaButton = new javax.swing.JButton();
        tablaUnidadesjScrollPane = new javax.swing.JScrollPane();
        unidadMedidaTable = new javax.swing.JTable();
        atrasUnidadMedidaButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Unidad de medida");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        nombreUnidadMedidaLabel.setText("Nombre: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        getContentPane().add(nombreUnidadMedidaLabel, gridBagConstraints);

        simboloUnidadMedidaLabel.setText("Símbolo:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        getContentPane().add(simboloUnidadMedidaLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 213;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        getContentPane().add(simboloTextField, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 213;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        getContentPane().add(nombreTextField, gridBagConstraints);

        guardarUnidadMedidaButton.setText("Guardar");
        guardarUnidadMedidaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarUnidadMedidaApretado(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 5;
        getContentPane().add(guardarUnidadMedidaButton, gridBagConstraints);

        eliminarUnidadMedidaButton.setText("Eliminar");
        eliminarUnidadMedidaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarUnidadMedidaApretado(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        getContentPane().add(eliminarUnidadMedidaButton, gridBagConstraints);

        unidadMedidaTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nombre unidad", "Símbolo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        unidadMedidaTable.getTableHeader().setReorderingAllowed(false);
        tablaUnidadesjScrollPane.setViewportView(unidadMedidaTable);
        if (unidadMedidaTable.getColumnModel().getColumnCount() > 0) {
            unidadMedidaTable.getColumnModel().getColumn(0).setResizable(false);
            unidadMedidaTable.getColumnModel().getColumn(1).setResizable(false);
        }

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(tablaUnidadesjScrollPane, gridBagConstraints);

        atrasUnidadMedidaButton.setText("Átras");
        atrasUnidadMedidaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAtrasApretado(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(29, 30, 11, 20);
        getContentPane().add(atrasUnidadMedidaButton, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonEliminarUnidadMedidaApretado(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarUnidadMedidaApretado
        // TODO add your handling code here:
    }//GEN-LAST:event_botonEliminarUnidadMedidaApretado

    private void botonGuardarUnidadMedidaApretado(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarUnidadMedidaApretado
        // TODO add your handling code here:
    }//GEN-LAST:event_botonGuardarUnidadMedidaApretado

    private void botonAtrasApretado(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAtrasApretado
        // TODO add your handling code here:
    }//GEN-LAST:event_botonAtrasApretado

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaUnidadMedida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaUnidadMedida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaUnidadMedida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaUnidadMedida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaUnidadMedida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atrasUnidadMedidaButton;
    private javax.swing.JButton eliminarUnidadMedidaButton;
    private javax.swing.JButton guardarUnidadMedidaButton;
    private javax.swing.JTextField nombreTextField;
    private javax.swing.JLabel nombreUnidadMedidaLabel;
    private javax.swing.JTextField simboloTextField;
    private javax.swing.JLabel simboloUnidadMedidaLabel;
    private javax.swing.JScrollPane tablaUnidadesjScrollPane;
    private javax.swing.JTable unidadMedidaTable;
    // End of variables declaration//GEN-END:variables
}
