/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.flatron.vistas;

/**
 *
 * @author laboratorio
 */
public class VistaUnidadMedida extends javax.swing.JFrame {

    /**
     * Creates new form VistaUnidadMedida
     */
    public VistaUnidadMedida() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombreUnidadMedidaLabel = new javax.swing.JLabel();
        simboloUnidadMedidaLabel = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        simboloUnidadMedidaTextField2 = new javax.swing.JTextField();
        guardarUnidadMedidaButton = new javax.swing.JButton();
        eliminarUnidadMedidaButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        unidadMedidaTable = new javax.swing.JTable();
        atrasUnidadMedidaButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Unidad de medida");

        nombreUnidadMedidaLabel.setText("Nombre: ");

        simboloUnidadMedidaLabel.setText("Símbolo:");

        guardarUnidadMedidaButton.setText("Guardar");
        guardarUnidadMedidaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarUnidadMedidaApretado(evt);
            }
        });

        eliminarUnidadMedidaButton.setText("Eliminar");
        eliminarUnidadMedidaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarUnidadMedidaApretado(evt);
            }
        });

        unidadMedidaTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nombre unidad", "Símbolo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        unidadMedidaTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(unidadMedidaTable);
        if (unidadMedidaTable.getColumnModel().getColumnCount() > 0) {
            unidadMedidaTable.getColumnModel().getColumn(0).setResizable(false);
            unidadMedidaTable.getColumnModel().getColumn(1).setResizable(false);
        }

        atrasUnidadMedidaButton.setText("Átras");
        atrasUnidadMedidaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAtrasApretado(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(atrasUnidadMedidaButton)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(simboloUnidadMedidaLabel)
                                .addComponent(nombreUnidadMedidaLabel))
                            .addGap(15, 15, 15)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField1)
                                .addComponent(simboloUnidadMedidaTextField2))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(eliminarUnidadMedidaButton)
                        .addGap(18, 18, 18)
                        .addComponent(guardarUnidadMedidaButton)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreUnidadMedidaLabel)
                    .addComponent(simboloUnidadMedidaTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(simboloUnidadMedidaLabel)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eliminarUnidadMedidaButton)
                    .addComponent(guardarUnidadMedidaButton))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(atrasUnidadMedidaButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonEliminarUnidadMedidaApretado(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarUnidadMedidaApretado
        // TODO add your handling code here:
    }//GEN-LAST:event_botonEliminarUnidadMedidaApretado

    private void botonGuardarUnidadMedidaApretado(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarUnidadMedidaApretado
        // TODO add your handling code here:
    }//GEN-LAST:event_botonGuardarUnidadMedidaApretado

    private void botonAtrasApretado(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAtrasApretado
        // TODO add your handling code here:
    }//GEN-LAST:event_botonAtrasApretado

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaUnidadMedida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaUnidadMedida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaUnidadMedida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaUnidadMedida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaUnidadMedida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atrasUnidadMedidaButton;
    private javax.swing.JButton eliminarUnidadMedidaButton;
    private javax.swing.JButton guardarUnidadMedidaButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel nombreUnidadMedidaLabel;
    private javax.swing.JLabel simboloUnidadMedidaLabel;
    private javax.swing.JTextField simboloUnidadMedidaTextField2;
    private javax.swing.JTable unidadMedidaTable;
    // End of variables declaration//GEN-END:variables
}
